config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users
  resources :vaults, except: [:edit] do 
  	member do
  	end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :vaults
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vault.rb
class Vault < ApplicationRecord
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	def after_sign_in_path_for(resource)
		vaults_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/vaults_controller.rb
class VaultsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_vault, except: [:index, :new, :create]

  def index
  	@vaults = current_user.vaults
  end

  def new
  	@vault = current_user.vaults.build
  end

  def show
  end

  def create 
  	@vault = current_user.vaults.build(vault_params)
  	if @vault.save
  		redirect_to vault_path(@vault)
  	else
  	  flash[:alert] = "Something went wrong..."
      render :new
  	end
  end

  private

  def set_vault
  	@vault = Vault.find(params[:id])
  end

  def vault_params
    params.require(:vault).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/vaults_helper.rb
module VaultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StorageApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'VaultStorage', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
      	<% if user_signed_in? %>
          <li><%= link_to 'My Vaults', vaults_path %></li>
        <% else %>
      	  <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/vaults/index.html.erb
<div class="row">
	<div class="col-md-9">
		<h1>My Vaults</h1>
	</div>
	<div class="col-md-3">
		<%= link_to 'Add New Vault', new_vault_path, class: "pull-right btn btn-primary" %>
	</div>
		<% @vaults.each do |vault| %>
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<%= link_to vault.title, vault %>
				</div>
				<div class="panel-body">
					<%= vault.description %>	
				</div>
			</div>
		</div>
		<% end %>

</div>

app/views/vaults/new.html.erb
<%= form_for @vault do |f| %>
	<%= f.text_field :title, placeholder: 'title' %>
	<%= f.submit 'Create Vault' %>
<% end %>

app/views/vaults/show.html.erb
<h1><%= @vault.title %></h1>